import json
import os
from datetime import datetime

def generate_report(project_name, status, security_stats, performance_stats, loot_items, suggestions):
    updated_at = datetime.now().strftime('%Y-%m-%d %H:%M')
    
    # 這裡放我們剛才設計的 HTML 模板，但將數據變量化
    template = f'''
    <!DOCTYPE html>
    <html lang="zh-TW">
    <head>
        <meta charset="UTF-8">
        <title>{project_name} 系統冒險檢測報告</title>
        <style>
            /* 這裡放之前的 CSS */
            :root {{ --bg: #0f0c29; --card: #1b1b2f; --primary: #00d2ff; --success: #39ff14; --warning: #ffbd39; --danger: #ff3131; --text: #ffffff; }}
            body {{ font-family: sans-serif; background: var(--bg); color: var(--text); display: flex; flex-direction: column; align-items: center; padding: 20px; }}
            .quest-card {{ background: var(--card); border: 2px solid var(--primary); border-radius: 15px; padding: 20px; margin-bottom: 20px; width: 100%; max-width: 800px; }}
            .loot-item {{ display: inline-block; background: #333; padding: 5px 10px; border-radius: 5px; margin: 5px; font-size: 0.9em; }}
        </style>
    </head>
    <body>
        <h1>{project_name} RAID REPORT</h1>
        <div class="status" style="color:var(--success); font-weight:bold; margin-bottom:20px;">[ {status} ] 最後掃描：{updated_at}</div>
        
        <div class="quest-card">
            <h3>🛡️ 安全防禦: {security_stats['level']}</h3>
            <p>戰利品: {" ".join([f'<span class="loot-item">{x}</span>' for x in loot_items])}</p>
        </div>

        <div class="quest-card">
            <h3>📜 改善建議</h3>
            {"".join([f'<p>• {x}</p>' for x in suggestions])}
        </div>
        
        <footer>GENERATED BY JOECLOW AI LAB</footer>
    </body>
    </html>
    '''
    
    with open(f'{project_name.lower()}_report.html', 'w') as f:
        f.write(template)
    print(f"✅ 報告已生成: {project_name.lower()}_report.html")

# 使用範例
if __name__ == "__main__":
    generate_report(
        "HIS", 
        "MISSION ACCOMPLISHED", 
        {"level": "SS"}, 
        {"speed": "1.2s"}, 
        ["HTTPS已驗證", "驗證碼門檻", "SSL憑證正常"],
        ["強制 HTTPS 跳轉", "Session 自動超時", "RWD 介面優化"]
    )
