#!/usr/bin/env python3
"""
Daily maintenance script for JoeClawSite
Runs: fetch (no auto-pull), run update_promotions.py, run update_html.py, py_compile checks,
optionally run autopep8 (in-place) and commit fixes locally (no push by default).
Writes a detailed log to logs/maintenance-YYYYMMDD.txt and a short suggestions file.
This version now supports optional auto-push to origin (enabled by default per user request).
"""
import os
import subprocess
import datetime
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOGDIR = ROOT / 'logs'
LOGDIR.mkdir(parents=True, exist_ok=True)
now = datetime.datetime.now()
date_str = now.strftime('%Y-%m-%d')
log_path = LOGDIR / f'maintenance-{date_str}.txt'
suggestions_path = LOGDIR / f'suggestions-{date_str}.txt'

def run(cmd, cwd=ROOT, check=False):
    try:
        p = subprocess.run(cmd, cwd=cwd, shell=True, capture_output=True, text=True, timeout=300)
        return p.returncode, p.stdout, p.stderr
    except Exception as e:
        return 1, '', str(e)

with open(log_path, 'a', encoding='utf-8') as L:
    L.write(f'=== Maintenance run: {now.isoformat()} ===\n')

    # 1) Git fetch (do not auto-pull by default)
    L.write('\n-- git fetch --\n')
    rc,out,err = run('git fetch --all')
    L.write(out + err + f'rc={rc}\n')

    # 2) Run update_promotions.py
    L.write('\n-- run update_promotions.py --\n')
    if (ROOT / 'update_promotions.py').exists():
        rc,out,err = run('python3 update_promotions.py')
        L.write(out + err + f'rc={rc}\n')
    else:
        L.write('update_promotions.py not found\n')

    # 3) Run update_html.py
    L.write('\n-- run update_html.py --\n')
    if (ROOT / 'update_html.py').exists():
        rc,out,err = run('python3 update_html.py')
        L.write(out + err + f'rc={rc}\n')
    else:
        L.write('update_html.py not found\n')

    # 4) Syntax-check all python files (py_compile)
    L.write('\n-- py_compile check --\n')
    rc,out,err = run("python3 -m py_compile $(find . -name '*.py' -not -path './venv/*')")
    L.write(out + err + f'rc={rc}\n')

    # 5) Run autopep8 if available (in-place) and commit changes locally
    L.write('\n-- autopep8 (in-place) --\n')
    rc,out,err = run('which autopep8 || true')
    if rc == 0 and out.strip():
        # apply to project python files (exclude venv)
        rc,out,err = run("autopep8 --in-place --aggressive --aggressive $(find . -name '*.py' -not -path './venv/*' -not -path './.git/*') || true")
        L.write(out + err + f'rc={rc}\n')
        # git add/commit if changes present
        rc,out,err = run('git status --porcelain')
        if out.strip():
            run('git add -A')
            cm = f'autopep8 fixes (maintenance {date_str})'
            rc,out,err = run(f'git commit -m "{cm}" || true')
            L.write('Committed autopep8 fixes\n' + out + err + f'rc={rc}\n')
        else:
            L.write('No python formatting changes found.\n')
    else:
        L.write('autopep8 not installed or not found in PATH.\n')

    # 6) Summarize recent server log errors (search for TRACEBACK or 5xx)
    L.write('\n-- scan status-server.log for errors --\n')
    ss = ROOT / 'logs' / 'status-server.log'
    if ss.exists():
        try:
            with open(ss, 'r', encoding='utf-8') as f:
                data = f.read()
            errors = []
            for line in data.splitlines()[-800:]:
                if 'Traceback' in line or 'ERROR' in line or ' 500 ' in line:
                    errors.append(line)
            if errors:
                L.write('Recent error lines:\n' + '\n'.join(errors) + '\n')
            else:
                L.write('No recent TRACEBACK/ERROR/5xx lines found in status-server.log\n')
        except Exception as e:
            L.write('Could not read status-server.log: ' + str(e) + '\n')
    else:
        L.write('status-server.log not found\n')

    # 7) Auto-push changes to origin main (user requested)
    L.write('\n-- auto-push to origin main --\n')
    rc_branch, out_branch, err_branch = run('git rev-parse --abbrev-ref HEAD')
    branch = out_branch.strip() if rc_branch==0 and out_branch.strip() else 'main'
    rc,out,err = run('git status --porcelain')
    if out.strip():
        L.write('Local changes present, attempting to push to origin '+branch+'\n')
        rc2,o2,e2 = run('git push origin '+branch)
        L.write(o2 + e2 + f'rc={rc2}\n')
    else:
        L.write('No local changes to push.\n')

    L.write('\n-- maintenance end --\n')

# write a simple suggestions seed (assistant will update daily when it runs)
with open(suggestions_path, 'w', encoding='utf-8') as S:
    S.write('Seed suggestions generated by assistant run at ' + now.isoformat() + '\n')
    S.write('\n- Consider adding concise KPI widgets (1-3 top metrics) with sparklines.\n')
    S.write('- Add configurable alerts/thresholds for major indices and promotions.\n')
    S.write('- Add a lightweight user preferences panel to toggle live refresh and category visibility.\n')

print('Maintenance run complete:', log_path)
